### ISSUE TITLE
00-anomaly-detection-tutorial: Container deployment failure Azure ML - AciDeploymentFailed

### ISSUE THREAD

**Issue by leestott** [Azure/ai-toolkit-iot-edge#22]
Recieve the following ERROR - Service deployment polling reached non-successful terminal state, current service state: Failed Operation ID: 43f65bff-fbd4-434f-bdd9-2af56ece7041 More information can be found using '.get_logs()' Error: { "code": "AciDeploymentFailed", "message": "Aci Deployment failed with exception: Your container application crashed. 

This may be caused by errors in your scoring file's init() function.\nPlease check the logs for your container instance: tempsensor-iotedge-ml-test1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. \nYou can also try to run image f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68 locally. Please refer to https://aka.ms/debugimage#service-launch-fails for more information.", "details": [ { "code": "CrashLoopBackOff", "message": "Your container application crashed. This may be caused by errors in your scoring file's init() function.\nPlease check the logs for your container instance: tempsensor-iotedge-ml-test1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. \nYou can also try to run image f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68 locally. Please refer to https://aka.ms/debugimage#service-launch-fails for more information." }, { "code": "AciDeploymentFailed", "message": "Your container application crashed. Please follow the steps to debug:\n1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. Please refer to https://aka.ms/debugimage#dockerlog for more information.\n2. If your container application crashed. This may be caused by errors in your scoring file's init() function. You can try debugging locally first. 

Please refer to https://aka.ms/debugimage#debug-locally for more information.\n3. View the diagnostic events to check status of container, it may help you to debug the issue. {\"restartCount\":3,\"currentState\":{\"state\":\"Waiting\",\"startTime\":null,\"exitCode\":null,\"finishTime\":null,\"detailStatus\":\"CrashLoopBackOff: Back-off 40s restarting failed\"},\"previousState\":{\"state\":\"Terminated\",\"startTime\":\"2020-09-01T12:51:21Z\",\"exitCode\":111,\"finishTime\":\"2020-09-01T12:51:26Z\",\"detailStatus\":\"Error\"},\"events\":[{\"count\":3,\"firstTimestamp\":\"2020-09-01T12:48:47Z\",\"lastTimestamp\":\"2020-09-01T12:50:50Z\",\"name\":\"Pulling\",\"message\":\"pulling image \\\"f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68\\\"\",\"type\":\"Normal\"},{\"count\":3,\"firstTimestamp\":\"2020-09-01T12:50:04Z\",\"lastTimestamp\":\"2020-09-01T12:50:50Z\",\"name\":\"Pulled\",\"message\":\"Successfully pulled image \\\"f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68\\\"\",\"type\":\"Normal\"},{\"count\":3,\"firstTimestamp\":\"2020-09-01T12:50:14Z\",\"lastTimestamp\":\"2020-09-01T12:50:50Z\",\"name\":\"Created\",\"message\":\"Created container\",\"type\":\"Normal\"},{\"count\":3,\"firstTimestamp\":\"2020-09-01T12:50:14Z\",\"lastTimestamp\":\"2020-09-01T12:50:50Z\",\"name\":\"Started\",\"message\":\"Started container\",\"type\":\"Normal\"},{\"count\":1,\"firstTimestamp\":\"2020-09-01T12:50:37Z\",\"lastTimestamp\":\"2020-09-01T12:50:37Z\",\"name\":\"BackOff\",\"message\":\"Back-off restarting failed container\",\"type\":\"Warning\"}]}" } ] } ERROR - Service deployment polling reached non-successful terminal state, current service state: Failed Operation ID: 43f65bff-fbd4-434f-bdd9-2af56ece7041 More information can be found using '.get_logs()' Error: { "code": "AciDeploymentFailed", "message": "Aci Deployment failed with exception: Your container application crashed. This may be caused by errors in your scoring file's init() function.\nPlease check the logs for your container instance: tempsensor-iotedge-ml-test1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. \nYou can also try to run image f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68 locally. Please refer to https://aka.ms/debugimage#service-launch-fails for more information.", "details": [ { "code": "CrashLoopBackOff", "message": "Your container application crashed. This may be caused by errors in your scoring file's init() function.\nPlease check the logs for your container instance: tempsensor-iotedge-ml-test1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. \nYou can also try to run image f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68 locally. Please refer to https://aka.ms/debugimage#service-launch-fails for more information." }, { "code": "AciDeploymentFailed", "message": "Your container application crashed. Please follow the steps to debug:\n1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. Please refer to https://aka.ms/debugimage#dockerlog for more information.\n2. If your container application crashed. This may be caused by errors in your scoring file's init() function. You can try debugging locally first. Please refer to https://aka.ms/debugimage#debug-locally for more information.\n3. View the diagnostic events to check status of container, it may help you to debug the issue. {\"restartCount\":3,\"currentState\":{\"state\":\"Waiting\",\"startTime\":null,\"exitCode\":null,\"finishTime\":null,\"detailStatus\":\"CrashLoopBackOff: Back-off 40s restarting failed\"},\"previousState\":{\"state\":\"Terminated\",\"startTime\":\"2020-09-01T12:51:21Z\",\"exitCode\":111,\"finishTime\":\"2020-09-01T12:51:26Z\",\"detailStatus\":\"Error\"},\"events\":[{\"count\":3,\"firstTimestamp\":\"2020-09-01T12:48:47Z\",\"lastTimestamp\":\"2020-09-01T12:50:50Z\",\"name\":\"Pulling\",\"message\":\"pulling image \\\"f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68\\\"\",\"type\":\"Normal\"},{\"count\":3,\"firstTimestamp\":\"2020-09-01T12:50:04Z\",\"lastTimestamp\":\"2020-09-01T12:50:50Z\",\"name\":\"Pulled\",\"message\":\"Successfully pulled image \\\"f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68\\\"\",\"type\":\"Normal\"},{\"count\":3,\"firstTimestamp\":\"2020-09-01T12:50:14Z\",\"lastTimestamp\":\"2020-09-01T12:50:50Z\",\"name\":\"Created\",\"message\":\"Created container\",\"type\":\"Normal\"},{\"count\":3,\"firstTimestamp\":\"2020-09-01T12:50:14Z\",\"lastTimestamp\":\"2020-09-01T12:50:50Z\",\"name\":\"Started\",\"message\":\"Started container\",\"type\":\"Normal\"},{\"count\":1,\"firstTimestamp\":\"2020-09-01T12:50:37Z\",\"lastTimestamp\":\"2020-09-01T12:50:37Z\",\"name\":\"BackOff\",\"message\":\"Back-off restarting failed container\",\"type\":\"Warning\"}]}" } ] } 
--------------------------------------------------------------------------- WebserviceException Traceback (most recent call last) /opt/conda/lib/python3.8/site-packages/azureml/core/webservice/webservice.py in wait_for_deployment(self, show_output) 667 --> 668 raise WebserviceException('Service deployment polling reached non-successful terminal state, current ' 669 'service state: {}\n' WebserviceException: WebserviceException: Message: Service deployment polling reached non-successful terminal state, current service state: Failed Operation ID: 43f65bff-fbd4-434f-bdd9-2af56ece7041 More information can be found using '.get_logs()' Error: { "code": "AciDeploymentFailed", "message": "Aci Deployment failed with exception: Your container application crashed. This may be caused by errors in your scoring file's init() function.\nPlease check the logs for your container instance: tempsensor-iotedge-ml-test1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. \nYou can also try to run image f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68 locally. Please refer to https://aka.ms/debugimage#service-launch-fails for more information.", "details": [ { "code": "CrashLoopBackOff", "message": "Your container application crashed. This may be caused by errors in your scoring file's init() function.\nPlease check the logs for your container instance: tempsensor-iotedge-ml-test1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. \nYou can also try to run image f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68 locally. Please refer to https://aka.ms/debugimage#service-launch-fails for more information." }, { "code": "AciDeploymentFailed", "message": "Your container application crashed. Please follow the steps to debug:\n1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. Please refer to https://aka.ms/debugimage#dockerlog for more information.\n2. If your container application crashed. This may be caused by errors in your scoring file's init() function. You can try debugging locally first. Please refer to https://aka.ms/debugimage#debug-locally for more information.\n3. View the diagnostic events to check status of container, it may help you to debug the issue. {\"restartCount\":3,\"currentState\":{\"state\":\"Waiting\",\"startTime\":null,\"exitCode\":null,\"finishTime\":null,\"detailStatus\":\"CrashLoopBackOff: Back-off 40s restarting failed\"},\"previousState\":{\"state\":\"Terminated\",\"startTime\":\"2020-09-01T12:51:21Z\",\"exitCode\":111,\"finishTime\":\"2020-09-01T12:51:26Z\",\"detailStatus\":\"Error\"},\"events\":[{\"count\":3,\"firstTimestamp\":\"2020-09-01T12:48:47Z\",\"lastTimestamp\":\"2020-09-01T12:50:50Z\",\"name\":\"Pulling\",\"message\":\"pulling image \\\"f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68\\\"\",\"type\":\"Normal\"},{\"count\":3,\"firstTimestamp\":\"2020-09-01T12:50:04Z\",\"lastTimestamp\":\"2020-09-01T12:50:50Z\",\"name\":\"Pulled\",\"message\":\"Successfully pulled image \\\"f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68\\\"\",\"type\":\"Normal\"},{\"count\":3,\"firstTimestamp\":\"2020-09-01T12:50:14Z\",\"lastTimestamp\":\"2020-09-01T12:50:50Z\",\"name\":\"Created\",\"message\":\"Created container\",\"type\":\"Normal\"},{\"count\":3,\"firstTimestamp\":\"2020-09-01T12:50:14Z\",\"lastTimestamp\":\"2020-09-01T12:50:50Z\",\"name\":\"Started\",\"message\":\"Started container\",\"type\":\"Normal\"},{\"count\":1,\"firstTimestamp\":\"2020-09-01T12:50:37Z\",\"lastTimestamp\":\"2020-09-01T12:50:37Z\",\"name\":\"BackOff\",\"message\":\"Back-off restarting failed container\",\"type\":\"Warning\"}]}" } ] } InnerException None ErrorResponse { "error": { "message": "Service deployment polling reached non-successful terminal state, current service state: Failed\nOperation ID: 43f65bff-fbd4-434f-bdd9-2af56ece7041\nMore information can be found using '.get_logs()'\nError:\n{\n \"code\": \"AciDeploymentFailed\",\n \"message\": \"Aci Deployment failed with exception: Your container application crashed. This may be caused by errors in your scoring file's init() function.\\nPlease check the logs for your container instance: tempsensor-iotedge-ml-test1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. \\nYou can also try to run image f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68 locally. Please refer to https://aka.ms/debugimage#service-launch-fails for more information.\",\n \"details\": [\n {\n \"code\": \"CrashLoopBackOff\",\n \"message\": \"Your container application crashed. This may be caused by errors in your scoring file's init() function.\\nPlease check the logs for your container instance: tempsensor-iotedge-ml-test1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. \\nYou can also try to run image f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68 locally. Please refer to https://aka.ms/debugimage#service-launch-fails for more information.\"\n },\n {\n \"code\": \"AciDeploymentFailed\",\n \"message\": \"Your container application crashed. Please follow the steps to debug:\\n1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. Please refer to https://aka.ms/debugimage#dockerlog for more information.\\n2. If your container application crashed. This may be caused by errors in your scoring file's init() function. You can try debugging locally first. Please refer to https://aka.ms/debugimage#debug-locally for more information.\\n3. View the diagnostic events to check status of container, it may help you to debug the issue. {\\\"restartCount\\\":3,\\\"currentState\\\":{\\\"state\\\":\\\"Waiting\\\",\\\"startTime\\\":null,\\\"exitCode\\\":null,\\\"finishTime\\\":null,\\\"detailStatus\\\":\\\"CrashLoopBackOff: Back-off 40s restarting failed\\\"},\\\"previousState\\\":{\\\"state\\\":\\\"Terminated\\\",\\\"startTime\\\":\\\"2020-09-01T12:51:21Z\\\",\\\"exitCode\\\":111,\\\"finishTime\\\":\\\"2020-09-01T12:51:26Z\\\",\\\"detailStatus\\\":\\\"Error\\\"},\\\"events\\\":[{\\\"count\\\":3,\\\"firstTimestamp\\\":\\\"2020-09-01T12:48:47Z\\\",\\\"lastTimestamp\\\":\\\"2020-09-01T12:50:50Z\\\",\\\"name\\\":\\\"Pulling\\\",\\\"message\\\":\\\"pulling image \\\\\\\"f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68\\\\\\\"\\\",\\\"type\\\":\\\"Normal\\\"},{\\\"count\\\":3,\\\"firstTimestamp\\\":\\\"2020-09-01T12:50:04Z\\\",\\\"lastTimestamp\\\":\\\"2020-09-01T12:50:50Z\\\",\\\"name\\\":\\\"Pulled\\\",\\\"message\\\":\\\"Successfully pulled image \\\\\\\"f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68\\\\\\\"\\\",\\\"type\\\":\\\"Normal\\\"},{\\\"count\\\":3,\\\"firstTimestamp\\\":\\\"2020-09-01T12:50:14Z\\\",\\\"lastTimestamp\\\":\\\"2020-09-01T12:50:50Z\\\",\\\"name\\\":\\\"Created\\\",\\\"message\\\":\\\"Created container\\\",\\\"type\\\":\\\"Normal\\\"},{\\\"count\\\":3,\\\"firstTimestamp\\\":\\\"2020-09-01T12:50:14Z\\\",\\\"lastTimestamp\\\":\\\"2020-09-01T12:50:50Z\\\",\\\"name\\\":\\\"Started\\\",\\\"message\\\":\\\"Started container\\\",\\\"type\\\":\\\"Normal\\\"},{\\\"count\\\":1,\\\"firstTimestamp\\\":\\\"2020-09-01T12:50:37Z\\\",\\\"lastTimestamp\\\":\\\"2020-09-01T12:50:37Z\\\",\\\"name\\\":\\\"BackOff\\\",\\\"message\\\":\\\"Back-off restarting failed container\\\",\\\"type\\\":\\\"Warning\\\"}]}\"\n }\n ]\n}" } } During handling of the above exception, another exception occurred: WebserviceException Traceback (most recent call last) in 7 name = aci_service_name, 8 workspace = ws) ----> 9 aci_service.wait_for_deployment(True) 10 print(aci_service.state) /opt/conda/lib/python3.8/site-packages/azureml/core/webservice/webservice.py in wait_for_deployment(self, show_output) 681 'Current state is {}'.format(self.state), logger=module_logger) 682 else: --> 683 raise WebserviceException(e.message, logger=module_logger) 684 685 def _wait_for_operation_to_complete(self, show_output): WebserviceException: WebserviceException: Message: Service deployment polling reached non-successful terminal state, current service state: Failed Operation ID: 43f65bff-fbd4-434f-bdd9-2af56ece7041 More information can be found using '.get_logs()' Error: { "code": "AciDeploymentFailed", "message": "Aci Deployment failed with exception: Your container application crashed. This may be caused by errors in your scoring file's init() function.\nPlease check the logs for your container instance: tempsensor-iotedge-ml-test1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. \nYou can also try to run image f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68 locally. Please refer to https://aka.ms/debugimage#service-launch-fails for more information.", "details": [ { "code": "CrashLoopBackOff", "message": "Your container application crashed. This may be caused by errors in your scoring file's init() function.\nPlease check the logs for your container instance: tempsensor-iotedge-ml-test1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. \nYou can also try to run image f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68 locally. Please refer to https://aka.ms/debugimage#service-launch-fails for more information." }, { "code": "AciDeploymentFailed", "message": "Your container application crashed. Please follow the steps to debug:\n1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. Please refer to https://aka.ms/debugimage#dockerlog for more information.\n2. If your container application crashed. This may be caused by errors in your scoring file's init() function. You can try debugging locally first. Please refer to https://aka.ms/debugimage#debug-locally for more information.\n3. View the diagnostic events to check status of container, it may help you to debug the issue. {\"restartCount\":3,\"currentState\":{\"state\":\"Waiting\",\"startTime\":null,\"exitCode\":null,\"finishTime\":null,\"detailStatus\":\"CrashLoopBackOff: Back-off 40s restarting failed\"},\"previousState\":{\"state\":\"Terminated\",\"startTime\":\"2020-09-01T12:51:21Z\",\"exitCode\":111,\"finishTime\":\"2020-09-01T12:51:26Z\",\"detailStatus\":\"Error\"},\"events\":[{\"count\":3,\"firstTimestamp\":\"2020-09-01T12:48:47Z\",\"lastTimestamp\":\"2020-09-01T12:50:50Z\",\"name\":\"Pulling\",\"message\":\"pulling image \\\"f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68\\\"\",\"type\":\"Normal\"},{\"count\":3,\"firstTimestamp\":\"2020-09-01T12:50:04Z\",\"lastTimestamp\":\"2020-09-01T12:50:50Z\",\"name\":\"Pulled\",\"message\":\"Successfully pulled image \\\"f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68\\\"\",\"type\":\"Normal\"},{\"count\":3,\"firstTimestamp\":\"2020-09-01T12:50:14Z\",\"lastTimestamp\":\"2020-09-01T12:50:50Z\",\"name\":\"Created\",\"message\":\"Created container\",\"type\":\"Normal\"},{\"count\":3,\"firstTimestamp\":\"2020-09-01T12:50:14Z\",\"lastTimestamp\":\"2020-09-01T12:50:50Z\",\"name\":\"Started\",\"message\":\"Started container\",\"type\":\"Normal\"},{\"count\":1,\"firstTimestamp\":\"2020-09-01T12:50:37Z\",\"lastTimestamp\":\"2020-09-01T12:50:37Z\",\"name\":\"BackOff\",\"message\":\"Back-off restarting failed container\",\"type\":\"Warning\"}]}" } ] } InnerException None ErrorResponse { "error": { "message": "Service deployment polling reached non-successful terminal state, current service state: Failed\nOperation ID: 43f65bff-fbd4-434f-bdd9-2af56ece7041\nMore information can be found using '.get_logs()'\nError:\n{\n \"code\": \"AciDeploymentFailed\",\n \"message\": \"Aci Deployment failed with exception: Your container application crashed. This may be caused by errors in your scoring file's init() function.\\nPlease check the logs for your container instance: tempsensor-iotedge-ml-test1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. \\nYou can also try to run image f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68 locally. Please refer to https://aka.ms/debugimage#service-launch-fails for more information.\",\n \"details\": [\n {\n \"code\": \"CrashLoopBackOff\",\n \"message\": \"Your container application crashed. This may be caused by errors in your scoring file's init() function.\\nPlease check the logs for your container instance: tempsensor-iotedge-ml-test1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. \\nYou can also try to run image f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68 locally. Please refer to https://aka.ms/debugimage#service-launch-fails for more information.\"\n },\n {\n \"code\": \"AciDeploymentFailed\",\n \"message\": \"Your container application crashed. Please follow the steps to debug:\\n1. From the AML SDK, you can run print(service.get_logs()) if you have service object to fetch the logs. Please refer to https://aka.ms/debugimage#dockerlog for more information.\\n2. If your container application crashed. This may be caused by errors in your scoring file's init() function. You can try debugging locally first. Please refer to https://aka.ms/debugimage#debug-locally for more information.\\n3. View the diagnostic events to check status of container, it may help you to debug the issue. {\\\"restartCount\\\":3,\\\"currentState\\\":{\\\"state\\\":\\\"Waiting\\\",\\\"startTime\\\":null,\\\"exitCode\\\":null,\\\"finishTime\\\":null,\\\"detailStatus\\\":\\\"CrashLoopBackOff: Back-off 40s restarting failed\\\"},\\\"previousState\\\":{\\\"state\\\":\\\"Terminated\\\",\\\"startTime\\\":\\\"2020-09-01T12:51:21Z\\\",\\\"exitCode\\\":111,\\\"finishTime\\\":\\\"2020-09-01T12:51:26Z\\\",\\\"detailStatus\\\":\\\"Error\\\"},\\\"events\\\":[{\\\"count\\\":3,\\\"firstTimestamp\\\":\\\"2020-09-01T12:48:47Z\\\",\\\"lastTimestamp\\\":\\\"2020-09-01T12:50:50Z\\\",\\\"name\\\":\\\"Pulling\\\",\\\"message\\\":\\\"pulling image \\\\\\\"f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68\\\\\\\"\\\",\\\"type\\\":\\\"Normal\\\"},{\\\"count\\\":3,\\\"firstTimestamp\\\":\\\"2020-09-01T12:50:04Z\\\",\\\"lastTimestamp\\\":\\\"2020-09-01T12:50:50Z\\\",\\\"name\\\":\\\"Pulled\\\",\\\"message\\\":\\\"Successfully pulled image \\\\\\\"f0ff5444e0bf4b99a497466dc8471dcb.azurecr.io/tempanomalydetection@sha256:e02bb4d4224980e098e369219f213847a86e4ae0e9636a011c9cce3f7680fa68\\\\\\\"\\\",\\\"type\\\":\\\"Normal\\\"},{\\\"count\\\":3,\\\"firstTimestamp\\\":\\\"2020-09-01T12:50:14Z\\\",\\\"lastTimestamp\\\":\\\"2020-09-01T12:50:50Z\\\",\\\"name\\\":\\\"Created\\\",\\\"message\\\":\\\"Created container\\\",\\\"type\\\":\\\"Normal\\\"},{\\\"count\\\":3,\\\"firstTimestamp\\\":\\\"2020-09-01T12:50:14Z\\\",\\\"lastTimestamp\\\":\\\"2020-09-01T12:50:50Z\\\",\\\"name\\\":\\\"Started\\\",\\\"message\\\":\\\"Started container\\\",\\\"type\\\":\\\"Normal\\\"},{\\\"count\\\":1,\\\"firstTimestamp\\\":\\\"2020-09-01T12:50:37Z\\\",\\\"lastTimestamp\\\":\\\"2020-09-01T12:50:37Z\\\",\\\"name\\\":\\\"BackOff\\\",\\\"message\\\":\\\"Back-off restarting failed container\\\",\\\"type\\\":\\\"Warning\\\"}]}\"\n }\n ]\n}" } }

**Comment by leestott** [comment]
so the issue is related 

Error message: Cannot uninstall 'PyYAML'

Azure Machine Learning SDK for Python: PyYAML is a distutils installed project. Therefore, we cannot accurately determine which files belong to it if there is a partial uninstall. To continue installing the SDK while ignoring this error, use:

Python

Copy
pip install --upgrade azureml-sdk[notebooks,automl] --ignore-installed PyYAML  So the creation of the docker image needs to be updated to include this

The ouput log .get_logs()' shows the following 


2020-09-10T06:54:58,830271429+00:00 - rsyslog/run 2020-09-10T06:54:58,832336644+00:00 - iot-server/run 2020-09-10T06:54:58,834377858+00:00 - gunicorn/run 2020-09-10T06:54:58,846991149+00:00 - nginx/run EdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set. Exiting... 2020-09-10T06:54:59,178452041+00:00 - iot-server/finish 1 0 2020-09-10T06:54:59,186163897+00:00 - Exit code 1 is normal. Not restarting iot-server. Starting gunicorn 19.9.0 Listening at: http://127.0.0.1:31311 (12) Using worker: sync worker timeout is set to 300 Booting worker with pid: 45 Exception in worker process Traceback (most recent call last): File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker worker.init_process() File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process self.load_wsgi() File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi self.wsgi = self.app.wsgi() File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi self.callable = self.load() File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load return self.load_wsgiapp() File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp return util.import_app(self.app_uri) File "/opt/miniconda/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app __import__(module) File "/var/azureml-server/wsgi.py", line 1, in <module> import create_app File "/var/azureml-server/create_app.py", line 3, in <module> from app import main File "/var/azureml-server/app.py", line 31, in <module> import main as user_main File "/var/azureml-app/main.py", line 12, in <module> driver_module_spec.loader.exec_module(driver_module) File "/var/azureml-app/iot_score.py", line 10, in <module> from azureml.core.model import Model File "/opt/miniconda/lib/python3.6/site-packages/azureml/core/__init__.py", line 13, in <module> from .workspace import Workspace File "/opt/miniconda/lib/python3.6/site-packages/azureml/core/workspace.py", line 34, in <module> from azureml.core.image import Image File "/opt/miniconda/lib/python3.6/site-packages/azureml/core/image/__init__.py", line 28, in <module> from .image import Image File "/opt/miniconda/lib/python3.6/site-packages/azureml/core/image/image.py", line 19, in <module> from azureml.core.model import Model File "/opt/miniconda/lib/python3.6/site-packages/azureml/core/model.py", line 39, in <module> from azureml.core.environment import Environment File "/opt/miniconda/lib/python3.6/site-packages/azureml/core/environment.py", line 31, in <module> from azureml.core.conda_dependencies import CondaDependencies, PYTHON_DEFAULT_VERSION File "/opt/miniconda/lib/python3.6/site-packages/azureml/core/conda_dependencies.py", line 11, in <module> **i**mport ruamel.yaml ModuleNotFoundError: No module named 'ruamel' Worker exiting (pid: 45) Shutting down:** Master Reason: Worker failed to boot. 2020-09-10T06:55:03,932157139+00:00 -** gunicorn/finish 3 0 2020-09-10T06:55:03,933713250+00:00 - Exit code 3 is not normal. Killing image.
